# Generated by Django 6.0.5 on 2026-05-29 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_adotante'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='castrado',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='genero',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='idade',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='tipo',
        ),
        migrations.AddField(
            model_name='animal',
            name='especie',
            field=models.CharField(choices=[('CACHORRO', 'Cachorro'), ('GATO', 'Gato'), ('COELHO', 'Coelho'), ('HAMSTER', 'Hamster'), ('PASSARO', 'Pássaro')], default='CACHORRO', max_length=20, verbose_name='espécie'),
        ),
        migrations.AddField(
            model_name='animal',
            name='esterilizacao',
            field=models.CharField(choices=[('SIM', 'Sim'), ('NAO', 'Não')], default='NAO', max_length=20, verbose_name='esterilização'),
        ),
        migrations.AddField(
            model_name='animal',
            name='nascimento',
            field=models.DateField(blank=True, null=True, verbose_name='data de nascimento'),
        ),
        migrations.AddField(
            model_name='animal',
            name='pelagem',
            field=models.CharField(choices=[('CURTA', 'Pelagem Curta'), ('MEDIA', 'Pelagem Média'), ('LONGA', 'Pelagem Longa'), ('AUSENTE', 'Sem Pelagem')], default='CURTA', max_length=20, verbose_name='pelagem'),
        ),
        migrations.AddField(
            model_name='animal',
            name='raca',
            field=models.CharField(choices=[('SRD', 'SRD (Sem Raça Definida)'), ('POODLE', 'Poodle'), ('LABRADOR', 'Labrador'), ('BULLDOG', 'Bulldog'), ('SHIH-TZU', 'Shih-Tzu'), ('SIAMES', 'Siamês'), ('PERSA', 'Persa'), ('MAINE-COON', 'Maine Coon'), ('OUTRO', 'Outro')], default='SRD', max_length=80, verbose_name='raça'),
        ),
        migrations.AddField(
            model_name='animal',
            name='sexo',
            field=models.CharField(choices=[('MACHO', 'Macho'), ('FEMEA', 'Fêmea')], default='MACHO', max_length=20, verbose_name='sexo'),
        ),
        migrations.AddField(
            model_name='animal',
            name='status',
            field=models.CharField(choices=[('VIVO', 'Vivo'), ('MORTO', 'Morto')], default='VIVO', max_length=20, verbose_name='status'),
        ),
    ]
