# Generated by Django 6.0.5 on 2026-05-30 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_animal_castrado_remove_animal_genero_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='especie',
            field=models.CharField(choices=[('CACHORRO', 'Cachorro'), ('GATO', 'Gato')], default='CACHORRO', max_length=20, verbose_name='espécie'),
        ),
    ]
