# Generated by Django 6.0.5 on 2026-05-30 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_animal_especie'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='animals/', verbose_name='foto'),
        ),
    ]
