# Generated by Django 6.0.5 on 2026-05-30 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_animal_adotante_adotado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='adotante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='animais', to='core.adotante'),
        ),
    ]
