# Generated by Django 6.0.5 on 2026-06-13 18:22

from django.db import migrations, models


def copy_nascimento_to_chegada(apps, schema_editor):
    Animal = apps.get_model('core', 'Animal')
    for animal in Animal.objects.all():
        if animal.nascimento and not animal.chegada:
            animal.chegada = animal.nascimento
            animal.save(update_fields=['chegada'])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_animal_data_obito'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='fotos_att',
        ),
        migrations.AddField(
            model_name='animal',
            name='chegada',
            field=models.DateField(blank=True, null=True, verbose_name='data de chegada'),
        ),
        migrations.RunPython(copy_nascimento_to_chegada, noop),
    ]
